FROM elasticsearch:2.3.4

### COMMON FOR ALL CONTAINERS

# ES
ARG ELK_ELASTICSEARCH_PORT
ENV ELK_ELASTICSEARCH_PORT $ELK_ELASTICSEARCH_PORT
ARG ELK_ELASTICSEARCH_HOST
ENV ELK_ELASTICSEARCH_HOST $ELK_ELASTICSEARCH_HOST
# LOGSTASH
ARG ELK_LOGSTASH_PORT
ENV ELK_LOGSTASH_PORT $ELK_LOGSTASH_PORT
# KIBANA
ARG ELK_KIBANA_PORT
ENV ELK_KIBANA_PORT $ELK_KIBANA_PORT

### END COMMON FOR ALL CONTAINERS ###


EXPOSE $ELK_ELASTICSEARCH_PORT

