---


elk:
  base_dir: sys
  dockerfiles_path: sys/dockerfiles
  build_args: --build-arg ELK_ELASTICSEARCH_HOST={{ containers.elk_elasticsearch.name }}
              --build-arg ELK_ELASTICSEARCH_PORT={{ containers.elk_elasticsearch.port }}
              --build-arg ELK_LOGSTASH_PORT={{ containers.elk_logstash.port }}
              --build-arg ELK_KIBANA_PORT={{ containers.elk_kibana.port }}
              --build-arg ELK_NGINX_PORT_HTTP={{ ansible_nginx_port_http }}
              --build-arg ELK_NGINX_PORT_HTTPS={{ ansible_nginx_port_https }}
  run_args: ""

weave:
  domain_name: weave.local
  group_name: mie
  launch_wait: 3

containers:
  elk_elasticsearch:
    name: elk-elasticsearch
    dockerfile: elk_elasticsearch.dockerfile
    port: 9200
    volume_args: "-v {{ volumes.elk_elasticsearch.name }}:{{ volumes.elk_elasticsearch.data_dir }}"
    retry_wait: 5
    retry_count: 6
    version: 2.3.4
  elk_logstash:
    name: elk-logstash
    dockerfile: elk_logstash.dockerfile
    port: 12201
    volume_args: "-v {{ volumes.elk_logstash.name }}:{{ volumes.elk_logstash.data_dir }}"
    run_command: "logstash -f config-dir/logstash.conf"
    version: 2.3.4
  elk_kibana:
    name: elk-kibana
    dockerfile: elk_kibana.dockerfile
    volume_args: "-v {{ volumes.elk_kibana.name }}:{{ volumes.elk_kibana.data_dir }}"
    port: 5601
    retry_wait: 5
    retry_count: 6
    version: 4.5.2
  elk_nginx:
    name: elk-nginx
    dockerfile: elk_nginx.dockerfile
    volume_args: ""
    retry_wait: 5
    retry_count: 6
    version: 1.11.1

volumes:
  elk_elasticsearch:
    name: elk_elasticsearch_data
    data_dir: /usr/share/elasticsearch/data
  elk_logstash:
    name: elk_logstash_data
    data_dir: /data
  elk_kibana:
    name: elk_kibana_data
    data_dir: /data

paths:
  docker: /usr/bin/docker
  git: /usr/bin/git
  weave: /usr/local/bin/weave
