---

# Stop ELK

- name: Stop nginx
  include: roles/ansible_nginx/tasks/teardown_containers.yml

- name: Stop Kibana
  include: roles/kibana/tasks/teardown_containers.yml

- name: Stop Logstash
  include: roles/logstash/tasks/teardown_containers.yml

- name: Stop Elasticsearch
  include: roles/elasticsearch/tasks/teardown_containers.yml
