---

- include: install_weave.yml
  when: weave_install is defined
  tags:
    - weave
    - install_weave

- include: weave_launch.yml
  when: weave_launch is defined
  tags:
    - weave
    - weave_launch

- name: Expose the weave port
  include: weave_expose.yml
  when: weave_expose is defined
  tags:
    - weave
    - weave_expose

- name: Connect to the remote host, but only if it is pre-defined
  include: weave_connect.yml
  vars:
    weave_hosts: "{{ hosts_to_connect }}"
  when: weave_connect is defined and hosts_to_connect is defined

- name: Prime the weave connections
  include: weave_prime.yml
  when: weave_prime is defined
  register: result

- debug: var=result

- include: weave_docker_args.yml
  tags:
    - weave
    - weave_argss
    - weave_docker_arg




