---

- name: Teardown the nginx containers if necessary
  include: teardown_containers.yml
  when: teardown_nginx_containers is defined
  tags:
    - teardown_containers
    - teardown_nginx_containers

- name: Build the nginx containers
  include: build_containers.yml
  when: build_containers is defined
  tags:
    - nginx
    - build
    - build_nginx

- name: Run the nginx containers
  include: run_containers.yml
  when: run_containers is defined
  tags:
    - nginx
    - run
    - run_nginx