---

# Check if the container is running.  If it is, dont' run it
- name: Check if {{ ansible_nginx_container_name }} is running
  include: roles/ansible_docker_utils/tasks/is_container_running.yml
  vars:
    docker_name: "{{ ansible_nginx_container_name }}"

# Pull the image from ECR
- name: Pull {{ ansible_nginx_container_name }} from ECR
  include: roles/ansible_aws/tasks/ansible_aws_pull_from_ecr.yml
  vars:
    ansible_aws_image_name: "{{ ansible_nginx_container_name }}"
    ansible_aws_image_tag: "{{ ansible_nginx_container_version }}"
  when: ansible_aws_pull_from_ecr is defined


# Run the container if it isn't running
- name: Launch the container {{ ansible_nginx_container_name }}
  include: roles/ansible_docker_utils/tasks/run_container.yml
  vars:
    docker_name: "{{ ansible_nginx_container_name }}"
    docker_domain_name: "{{ ansible_nginx_weave_domain }}"
    docker_volume_args: "{{ ansible_nginx_volume_args }}"
    docker_extra_args: "-d
                        --restart=always
                        -p {{ ansible_nginx_port_http }}:{{ ansible_nginx_port_http }}
                        -p {{ ansible_nginx_port_https }}:{{ ansible_nginx_port_https }}
                        {{ ansible_nginx_weave_docker_args }}"
  register: result
  when: "not {{docker_container_is_running }}"

# Check if nginx is up
- name: Check if {{ ansible_nginx_container_namee }} is up
  include: roles/ansible_docker_utils/tasks/is_nginx_up.yml
  vars:
    docker_name: "{{ ansible_nginx_container_name }}"
    docker_port: "{{ ansible_nginx_port_http }}"
    docker_retries: "{{ ansible_nginx_retry_count }}"
    docker_delay: "{{ ansible_nginx_retry_wait }}"
    docker_auth_required: true
