---

- name: Stop the nginx containers
  include: roles/ansible_docker_utils/tasks/stop_and_remove_container.yml
  vars:
    docker_name: "{{ item }}"
  with_items:
    - "{{ ansible_nginx_container_name }}"
  register: result

- debug: var=result.stdout_lines