#!/usr/bin/env /usr/bin/ansible-playbook
---

- hosts: elk
  become: yes
  become_method: sudo
  vars_files:
    - "{{ elk_config_file }}"
  vars:
    ansible_aws_login_to_ecr: yes
    ansible_aws_pull_from_ecr: yes
    run_containers: yes
  roles:
    - baseline
    - common
    - ansible_docker_utils
    - ansible_weave
    - role: ansible_aws
      ansible_aws_load_config: true
      ansible_aws_config_file: "{{ playbook_dir }}/{{ elk_aws_params_file }}"

    # Per instance items
    - elasticsearch
    - logstash
    - kibana
    - role: ansible_nginx
      ansible_nginx_container_name: "{{ containers.elk_nginx.name }}"
      ansible_nginx_container_version: "{{ containers.elk_nginx.version }}"
      ansible_nginx_volume_args: "{{ containers.elk_nginx.volume_args }}"
      ansible_nginx_retry_count: "{{ containers.elk_nginx.retry_count }}"
      ansible_nginx_retry_wait: "{{ containers.elk_nginx.retry_wait }}"
      ansible_nginx_weave_domain: "{{ weave.domain_name }}"
      ansible_nginx_weave_docker_args: "{{ weave_docker_args }}"
      ansible_nginx_dockerfile: "{{ containers.elk_nginx.dockerfile }}"
      ansible_nginx_build_args: "{{ elk.build_args }}"
