#!/usr/bin/env /usr/bin/ansible-playbook
---

- hosts: localhost
  become: yes
  become_method: sudo
  vars_files:
    - ansible_aws_params.yml
  vars:
    aws_get_info: yes
  roles:
    #- baseline
    - common
    - ansible_docker_utils
    - ansible_weave
    # Get info for default servers
    - role: ansible_aws
      aws_server_type: "{{ ansible_aws_servers.elk.name }}"
      aws_instance_count: "{{ ansible_aws_servers.elk.count }}"
      aws_instance_type: "{{ ansible_aws_servers.elk.instance_type }}"


- hosts: "{{ ansible_aws_servers.elk.name }}"
  become: yes
  become_method: sudo
  vars_files:
    - ansible_aws_params.yml
  roles:
    - common
    - ansible_docker_utils
    - ansible_weave
    - teardown