#!/usr/bin/env /usr/bin/ansible-playbook
---

- hosts: elk
  become: yes
  become_method: sudo
  vars_files:
    - "{{ elk_config_file }}"
  roles:
    - common
    - ansible_docker_utils
    - ansible_weave
    - role: teardown
      ansible_nginx_container_name: "{{ containers.elk_nginx.name }}"