#!/usr/bin/env /usr/bin/ansible-playbook
---

- hosts: localhost
  become: yes
  become_method: sudo
  roles:
    - baseline
    - common
    - ansible_weave
    - elasticsearch
    - logstash
    - kibana