#!/usr/bin/env /usr/bin/ansible-playbook
---

- hosts: localhost
  become: yes
  become_method: sudo
  vars:
    weave_expose: yes
  roles:
    - common
    - weave
    - elasticsearch
    - logstash
    - kibana