---

# Check if the container is running.  If it is, dont' run it
- name: Check if {{ containers.elk_kibana.name }} is running
  include: roles/ansible_docker_utils/tasks/is_container_running.yml
  vars:
    docker_name: "{{ containers.elk_kibana.name }}"

# Pull the image from ECR
- name: Pull {{ containers.elk_logstash.name }} from ECR
  include: roles/ansible_aws/tasks/aws_pull_from_ecr.yml
  vars:
    aws_image_name: "{{ containers.elk_kibana.name }}"
    aws_image_tag: "{{ containers.elk_kibana.version }}"
  when: aws_pull_from_ecr is defined


# Run the container if it isn't running
- name: Launch the container {{ containers.elk_kibana.name }}
  include: roles/ansible_docker_utils/tasks/run_container.yml
  vars:
    docker_name: "{{ containers.elk_kibana.name }}"
    docker_domain_name: "{{ weave.domain_name }}"
    docker_volume_args: "{{ containers.elk_kibana.volume_args }}"
    docker_extra_args: "-d
                        -p {{ containers.elk_kibana.port }}:{{ containers.elk_kibana.port }}
                        --restart=always
                        {{ weave_docker_args }}"
  register: result
  when: "not {{docker_container_is_running }}"
