---

- name: Populate and copy the Logstash config
  template:
    src: logstash.conf.j2
    dest: "{{ elk.base_dir }}/logstash/logstash.conf"

- name: Build the Logstash container
  include: roles/ansible_docker_utils/tasks/build_container.yml
  vars:
    docker_name: "{{ containers.elk_logstash.name }}"
    docker_dockerfile: "{{ elk.dockerfiles_path }}/{{ containers.elk_logstash.dockerfile }}"
    docker_build_args: "{{ elk.build_args }}"
    docker_base_dir: "{{ elk.base_dir }}"

#- debug: var=docker_result.stdout_lines

